Feature/addproductbutton
First-Plug/First-Plug-Platform-Client pull request #159
Opened 2024-04-25 16:07 UTC by MercedesPoisson

FP-82: Added product button to DataStock and EmptyCard components

2024-04-25 18:22 UTC, Francisco-Villanueva commented on src/common/EmptyCard.tsx
> +            icon={<AddIcon />}
Aca deberíamos usar el `additionalButtonIcon`

2024-04-25 19:18 UTC, First-Plug requested changes

2024-04-25 19:18 UTC, First-Plug commented on src/common/EmptyCard.tsx
> +            onClick={() => {}}
What's this supposed to do?

2024-04-25 19:18 UTC, First-Plug commented on src/app/home/my-stock/DataStock.tsx
> +            // onClick={() => setAside("AddStock")}
Aren't we missing the onClick?

2024-04-29 20:46 UTC, First-Plug approved these changes

2024-04-29 20:46 UTC, merged